### ISSUE TITLE
What's the easiest way to write validations that depend on other form fields?

### ISSUE THREAD

**Issue by saurabhnanda** [reygoch/valor#3]
For example, validating that toDate >= fromDate ?

**Comment by mastarija** [comment]
@saurabhnanda say you have this data type:

```haskell
data Something = Something
  { toDate   :: UTCTime
  , fromDate :: UTCTime
  } deriving ( Eq, Show, Generic )
```

Then I'd construct error type like this:

```haskell
data SomethingError = SomethingError
  { toDate    :: Maybe String
  , fromDate  :: Maybe String
  , toGTEfrom :: Maybe String
  } deriving ( Eq, Show, Generic )
```

And I'd do my validation like this:

```haskell
getToFrom :: Something -> (UTCTime, UTCTime)
getToFrom s = ( toDate s, fromDate s )

checkToFrom :: Monad m => (UTCTime, UTCTime) -> ExceptT [String] m (UTCTime, UTCTime)
checkToFrom tf@(to, from) = if to >= from
    then pure tf
    else throwE "to >= from is false"

somethingValidator :: Monad m => Validator Something m SomethingError
somethingValidator = SomethingError
  <$> check  toDate someCheck
  <*> checks fromDate [someOtherCheck1, someOtherCheck2]
  <*> check  getToFrom checkToFrom
```

Also, remember that you can use custom monad in your validators through `ExceptT` monad transformer, so if you need to validate something depending on how a previous test has passed, you can use a state monad to remember the result of some other test and access the data from it.

Just to summarize the answer to your question. You are not limited to just field selectors, from the data type you are validating. `check` and `checks` functions accept any function which takes in `Something` and returns some other type which can then be forwarded to the "checking" function. You can extract what ever data you want and pass it to the validator just like I did with `getToFrom`.
